ARMEL KALALA KAYEMBE

ARNAULD KABEYA MULEBA

BENITHA KALANGA KALONGI

Master 1 / IA

In [2]:
# importation des bibliothèque
import pandas as pd

In [3]:
# téléchargements du dataset
data = pd.read_csv('Grammy Award Nominees and Winners 1958-2024.csv')

In [4]:
# affichage du dataset
data

,Unnamed: 0,Year,Ceremony,Award ID,Award Type,Award Name,Work,Nominee,Winner
0,0,1958,1,587,Work,Best Recording For Children,Childrens' Marching Song (Album),Cyril Stapleton,False
1,1,1958,1,587,Work,Best Recording For Children,"Mommy, Give Me A Drinka Water (Album)",Danny Kaye,False
2,2,1958,1,587,Work,Best Recording For Children,The Witch Doctor,David Seville And The Chipmunks,False
3,3,1958,1,587,Work,Best Recording For Children,Tubby The Tuba,Jose Ferrer,False
4,4,1958,1,587,Work,Best Recording For Children,Fun In Shariland (Album),Shari Lewis And Lambchop,False
...,...,...,...,...,...,...,...,...,...
25300,25300,2024,67,2432,Work,Best Dance Pop Recording,"yes, and?",Ariana Grande,False
25301,25301,2024,67,2432,Work,Best Dance Pop Recording,L’AMOUR DE MA VIE [OVER NOW EXTENDED EDIT],Billie Eilish,False
25302,25302,2024,67,2432,Work,Best Dance Pop Recording,Make You Mine,Madison Beer,False
25303,25303,2024,67,2432,Work,Best Dance Pop Recording,Got Me Started,Troye Sivan,False
25304,25304,2024,67,2432,Work,Best Dance Pop Recording,Von dutch,Charli xcx,True

In [5]:
# renomer les colonnes en français
data.rename(columns={
    'Year':'Annee', 
    'Ceremony':'Ceromonie',
    'Award ID':'Prix ID',
    'Award Type':'Type_prix',
    'Award Name':'Nom_prix',
    'Work':'Travail',
    'Nominee':'Candidate',
    'Winner':'Gagnante',
},inplace=True)

In [6]:
# suppression de la colonne d'index inutile si présente
if 'Unnamed: 0' in data.columns:
    data.drop(columns=['Unnamed: 0'], inplace=True)

In [7]:
# affichage des 5 premières lignes
print(data.head())

   Annee  Ceromonie  Prix ID Type_prix                     Nom_prix  \
0   1958          1      587      Work  Best Recording For Children
1   1958          1      587      Work  Best Recording For Children
2   1958          1      587      Work  Best Recording For Children
3   1958          1      587      Work  Best Recording For Children
4   1958          1      587      Work  Best Recording For Children

                                 Travail                        Candidate  \
0       Childrens' Marching Song (Album)                  Cyril Stapleton
1  Mommy, Give Me A Drinka Water (Album)                       Danny Kaye
2                       The Witch Doctor  David Seville And The Chipmunks
3                         Tubby The Tuba                      Jose Ferrer
4               Fun In Shariland (Album)         Shari Lewis And Lambchop

   Gagnante
0     False
1     False
2     False
3     False
4     False

In [8]:
# dimension du dataset
data.shape

(25305, 8)

In [9]:
# nom des colonnes
data.columns

Index(['Annee', 'Ceromonie', 'Prix ID', 'Type_prix', 'Nom_prix', 'Travail',
       'Candidate', 'Gagnante'],
      dtype='object')

In [10]:
# affichage du dataset
data

,Annee,Ceromonie,Prix ID,Type_prix,Nom_prix,Travail,Candidate,Gagnante
0,1958,1,587,Work,Best Recording For Children,Childrens' Marching Song (Album),Cyril Stapleton,False
1,1958,1,587,Work,Best Recording For Children,"Mommy, Give Me A Drinka Water (Album)",Danny Kaye,False
2,1958,1,587,Work,Best Recording For Children,The Witch Doctor,David Seville And The Chipmunks,False
3,1958,1,587,Work,Best Recording For Children,Tubby The Tuba,Jose Ferrer,False
4,1958,1,587,Work,Best Recording For Children,Fun In Shariland (Album),Shari Lewis And Lambchop,False
...,...,...,...,...,...,...,...,...
25300,2024,67,2432,Work,Best Dance Pop Recording,"yes, and?",Ariana Grande,False
25301,2024,67,2432,Work,Best Dance Pop Recording,L’AMOUR DE MA VIE [OVER NOW EXTENDED EDIT],Billie Eilish,False
25302,2024,67,2432,Work,Best Dance Pop Recording,Make You Mine,Madison Beer,False
25303,2024,67,2432,Work,Best Dance Pop Recording,Got Me Started,Troye Sivan,False
25304,2024,67,2432,Work,Best Dance Pop Recording,Von dutch,Charli xcx,True

In [11]:
# information générales du dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25305 entries, 0 to 25304
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Annee      25305 non-null  int64
 1   Ceromonie  25305 non-null  int64
 2   Prix ID    25305 non-null  int64
 3   Type_prix  25305 non-null  object
 4   Nom_prix   25305 non-null  object
 5   Travail    24412 non-null  object
 6   Candidate  25305 non-null  object
 7   Gagnante   25305 non-null  bool
dtypes: bool(1), int64(3), object(4)
memory usage: 1.4+ MB

In [12]:
# données manquantes 
data.isnull().sum()

Annee          0
Ceromonie      0
Prix ID        0
Type_prix      0
Nom_prix       0
Travail      893
Candidate      0
Gagnante       0
dtype: int64

In [13]:
# statistique du dataset
data.describe()

              Annee     Ceromonie       Prix ID
count  25305.000000  25305.000000  25305.000000
mean    1995.793756     38.793756    672.282988
std       17.959109     17.959109    120.804628
min     1958.000000      1.000000    584.000000
25%     1982.000000     25.000000    614.000000
50%     1998.000000     41.000000    661.000000
75%     2010.000000     53.000000    701.000000
max     2024.000000     67.000000   2432.000000

In [14]:
# statistique sur la colonne Annee
print(data['Annee'].describe())

count    25305.000000
mean      1995.793756
std         17.959109
min       1958.000000
25%       1982.000000
50%       1998.000000
75%       2010.000000
max       2024.000000
Name: Annee, dtype: float64

In [15]:
# valeurs unique de la gagnante
data['Gagnante'].unique()

array([False,  True])

In [16]:
# nombre des doublons
data.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
25300    False
25301    False
25302    False
25303    False
25304    False
Length: 25305, dtype: bool

In [17]:
# doublons exacts
data.duplicated().sum()

0

In [18]:
# combien de gagnats par anneé et prix
winners_per_award=data[data['Gagnante']==True].groupby(['Annee', 'Nom_prix']).size()
multiple_winners=winners_per_award[winners_per_award>1]
multiple_winners

Annee  Nom_prix
1964   Best Engineered Recording    2
1978   Album Of The Year            2
dtype: int64

In [19]:
# supprimer les lignes trop vides 
data.dropna(subset=['Nom_prix', 'Candidate'],)

,Annee,Ceromonie,Prix ID,Type_prix,Nom_prix,Travail,Candidate,Gagnante
0,1958,1,587,Work,Best Recording For Children,Childrens' Marching Song (Album),Cyril Stapleton,False
1,1958,1,587,Work,Best Recording For Children,"Mommy, Give Me A Drinka Water (Album)",Danny Kaye,False
2,1958,1,587,Work,Best Recording For Children,The Witch Doctor,David Seville And The Chipmunks,False
3,1958,1,587,Work,Best Recording For Children,Tubby The Tuba,Jose Ferrer,False
4,1958,1,587,Work,Best Recording For Children,Fun In Shariland (Album),Shari Lewis And Lambchop,False
...,...,...,...,...,...,...,...,...
25300,2024,67,2432,Work,Best Dance Pop Recording,"yes, and?",Ariana Grande,False
25301,2024,67,2432,Work,Best Dance Pop Recording,L’AMOUR DE MA VIE [OVER NOW EXTENDED EDIT],Billie Eilish,False
25302,2024,67,2432,Work,Best Dance Pop Recording,Make You Mine,Madison Beer,False
25303,2024,67,2432,Work,Best Dance Pop Recording,Got Me Started,Troye Sivan,False
25304,2024,67,2432,Work,Best Dance Pop Recording,Von dutch,Charli xcx,True

In [20]:
# remplacer les NAN dans la colonne travail
data['Travail'].fillna('Inconnu',inplace=True)

In [21]:
# données manquantes 
data.isnull().sum()

Annee        0
Ceromonie    0
Prix ID      0
Type_prix    0
Nom_prix     0
Travail      0
Candidate    0
Gagnante     0
dtype: int64

In [22]:
data.sample(25)

,Annee,Ceromonie,Prix ID,Type_prix,Nom_prix,Travail,Candidate,Gagnante
15601,2004,47,633,Work,"Best Southern, Country, Or Bluegrass Gospel Album",Driven,The Crabb Family,False
2215,1967,10,684,Work,Best Contemporary Group Performance (Vocal Or ...,Sgt. Pepper's Lonely Hearts Club Band,The Beatles,False
25124,2024,67,749,Work,Best Dance/Electronic Album,Telos,Zedd,False
7294,1985,28,649,Work,"Best Soul Gospel Performance By A Duo, Group, ...",Tomorrow (Track),Carvin Winans & Marvin Winans,False
1156,1963,6,678,Work,"Best Vocal Performance, Female",I'm A Woman (Album),Peggy Lee,False
22340,2018,61,711,Work,Best Traditional Pop Vocal Album,Standards (Deluxe),Seal,False
15846,2004,47,726,Work,Best Tejano Album,Takin' On The World,Stefani Montiel,False
14079,2001,44,662,Work,Best Latin Jazz Album,Vol. 3: New Congo Square,Los Hombres Calientes - Irvin Mayfield & Bill ...,False
6020,1981,24,685,Work,Best Engineered Recording - Non-Classical,The Dude (Album),"Bruce Swedien, engineer (Quincy Jones)",False
16100,2005,48,626,Work,Best Contemporary Folk Album,Why Should The Fire Die?,Nickel Creek,False
21151,2015,58,765,Work,Best Classical Instrumental Solo,"Mozart: Keyboard Music, Vol. 7",Kristian Bezuidenhout,False
16946,2006,49,739,Work,"Best Remixed Recording, Non-Classical",World Hold On (E-Smoove Remix),"E-Smoove, remixer (Bob Sinclar)",False
7639,1986,29,649,Work,"Best Soul Gospel Performance By A Duo, Group, ...",James Cleveland And The Southern California Co...,James Cleveland And The Southern California Co...,False
9658,1991,34,687,Work,"Best Engineered Recording, Classical",Bernstein: Candide,"Gregor Zielinsky, engineer (Leonard Bernstein,...",True
21950,2017,60,738,Work,Best Rap/Sung Performance,Love Galore,SZA Featuring Travis Scott,False
6861,1984,27,618,Work,Best Arrangement On An Instrumental,Cameo For Flute... \,"Henry Mancini, arranger (James Galway And Henr...",False
18777,2010,53,610,Work,Country Album,You Get What You Give,Zac Brown Band,False
3052,1971,14,605,Work,"Best Country Vocal Performance, Male",Kiss An Angel Good Morning (Single),Charley Pride,False
8575,1988,31,717,Work,Best Rap Performance,Wild Wild West (Track),Kool Moe Dee,False
11329,1995,38,688,Nominee,Classical Producer Of The Year,Inconnu,John Fraser,False
21738,2017,60,613,Work,Best Score Soundtrack For Visual Media,Hidden Figures,"Benjamin Wallfisch, Pharrell Williams & Hans Z...",False
19718,2012,55,630,Nominee,Best New Artist,Inconnu,Hunter Hayes,False
8560,1988,31,708,Work,Best Spoken Word Or Non-Musical Recording,The Screwtape Letters,John Cleese,False
21135,2015,58,762,Work,Best Americana Album,The Traveling Kind,Emmylou Harris & Rodney Crowell,False
10439,1993,36,680,Work,Best Pop Performance By A Duo Or Group With Vocal,Man On The Moon (Single),R.E.M.,False

Dans le cadre de ce travail sur les Grammy Awards, il était essentiel de préparer convenablement les données pour :
S’assurer de la cohérence des colonnes et des noms.
Éliminer les colonnes inutiles.
Valider la complétude et l’exactitude des informations avant les analyses exploratoires.

Problèmes rencontrés et gestion

1️⃣ Problème de Complétude
Définition : La complétude mesure si toutes les données nécessaires sont présentes.
Observation : Dans le fichier importé, il y avait une colonne inutile (comme Unnamed: 0) ou des cellules vides dans la colonne importante (ex : Work).
Solution mise en œuvre : Suppression de la colonne Unnamed: 0 si présente et la suppression des valeurs manquantes sur la colonne work.


2️⃣ Problème de Validité
Définition : La validité vérifie si les valeurs sont acceptables et dans le bon format.
Observation : il n’y a pas des problèmes de validité (ex : la plage des années est bien comprise entre 1958-2024, la colonne Gagnante est bien de type booléenne).



3️⃣ Problème d’Exactitude
Définition : L’exactitude correspond à la fidélité des données par rapport à la réalité.
Observation : Difficile à vérifier directement sans comparer avec une source officielle des Grammy Awards. Mais en renommant les colonnes et en visualisant le contenu avec head() et shape, une première vérification a été amorcée.
Ce qu'on aurait pu faire : Vérifier l'absence de doublons dans des colonnes censées être uniques (par exemple le couple Annee et Nom_prix).


4️⃣ Problème de Cohérence
Définition : La cohérence concerne l’harmonie logique entre différentes colonnes et lignes.
Observation : Les valeurs de Winner (par exemple : 0 ou 1, True ou False, Oui ou Non) doivent être uniformes.
Solution possible : Vérification des valeurs uniques :
print(data['Gagnante'].unique())


Conclusion
Ce travail de préparation des données est conforme aux recommandations qui insistent sur l'importance de la phase de nettoyage avant toute exploitation analytique. Les opérations réalisées ici ont permis de :
Clarifier la structure des données.
Améliorer leur complétude.
Garantir une première validation de la cohérence.